/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.bandpowercalc;

public class BandpowerCalc {
  public static void fft_bandpower_calculate(double[] data, double Fs, double[] band, SWIGTYPE_p_double totalpower, SWIGTYPE_p_double pband) {
    BandpowerCalcJNI.fft_bandpower_calculate(data, Fs, band, SWIGTYPE_p_double.getCPtr(totalpower), SWIGTYPE_p_double.getCPtr(pband));
  }

  public static SWIGTYPE_p_double new_doubleArray(int nelements) {
    long cPtr = BandpowerCalcJNI.new_doubleArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_doubleArray(SWIGTYPE_p_double ary) {
    BandpowerCalcJNI.delete_doubleArray(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double doubleArray_getitem(SWIGTYPE_p_double ary, int index) {
    return BandpowerCalcJNI.doubleArray_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void doubleArray_setitem(SWIGTYPE_p_double ary, int index, double value) {
    BandpowerCalcJNI.doubleArray_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

}
