/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.matrixmultiplication;

public class MatrixMultiplication {
  public static void matrix_multiplication(double[] a, double[] b, double[] c) {
    MatrixMultiplicationJNI.matrix_multiplication(a, b, c);
  }

}
