/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.getcoherence;

public class GetCoherence {
  public static void get_coherence(double[] x, double[] y, double fs, double[] mscxy, double[] frequency_list) {
    GetCoherenceJNI.get_coherence(x, y, fs, mscxy, frequency_list);
  }

  public static SWIGTYPE_p_double new_doubleArray(int nelements) {
    long cPtr = GetCoherenceJNI.new_doubleArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_doubleArray(SWIGTYPE_p_double ary) {
    GetCoherenceJNI.delete_doubleArray(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double doubleArray_getitem(SWIGTYPE_p_double ary, int index) {
    return GetCoherenceJNI.doubleArray_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void doubleArray_setitem(SWIGTYPE_p_double ary, int index, double value) {
    GetCoherenceJNI.doubleArray_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

}
